# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI

on:
  #schedule:
  #  - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h

      - name: Update feeds
        run: |
          sed -i 's/src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          #
          # ========================固件定制部分========================
          #
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7620=y
          CONFIG_TARGET_ramips_mt7620_DEVICE_hiwifi_hc5661=y
          CONFIG_LIBSODIUM_MINIMAL=y
          CONFIG_PACKAGE_bash=m
          CONFIG_PACKAGE_boost=m
          CONFIG_PACKAGE_boost-date_time=m
          CONFIG_PACKAGE_boost-program_options=m
          CONFIG_PACKAGE_boost-system=m
          CONFIG_PACKAGE_ca-bundle=m
          CONFIG_PACKAGE_coreutils=m
          CONFIG_PACKAGE_coreutils-base64=m
          CONFIG_PACKAGE_dns2socks=m
          # CONFIG_PACKAGE_etherwake is not set
          CONFIG_PACKAGE_ipset=m
          CONFIG_PACKAGE_ipt2socks=m
          CONFIG_PACKAGE_iptables-mod-tproxy=m
          CONFIG_PACKAGE_kcptun-client=m
          CONFIG_PACKAGE_kmod-ip6tables=m
          CONFIG_PACKAGE_kmod-ipt-tproxy=m
          CONFIG_PACKAGE_kmod-nf-ipt6=m
          CONFIG_PACKAGE_kmod-nf-reject6=m
          CONFIG_PACKAGE_libatomic=m
          CONFIG_PACKAGE_libbz2=m
          CONFIG_PACKAGE_libdb47=m
          CONFIG_PACKAGE_libev=m
          CONFIG_PACKAGE_libevent2=m
          CONFIG_PACKAGE_libffi=m
          CONFIG_PACKAGE_libgdbm=m
          CONFIG_PACKAGE_libipset=m
          CONFIG_PACKAGE_liblzma=m
          CONFIG_PACKAGE_libmaxminddb=m
          CONFIG_PACKAGE_libmbedtls=m
          CONFIG_PACKAGE_libmnl=m
          CONFIG_PACKAGE_libncurses=m
          CONFIG_PACKAGE_libnss=m
          CONFIG_PACKAGE_libreadline=m
          CONFIG_PACKAGE_libsodium=m
          CONFIG_PACKAGE_libsqlite3=m
          CONFIG_PACKAGE_libstdcpp=m
          CONFIG_PACKAGE_libxml2=m
          CONFIG_PACKAGE_lua-maxminddb=m
          CONFIG_PACKAGE_luasocket=m
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          # CONFIG_PACKAGE_luci-app-arpbind is not set
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_fuse-utils is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
          CONFIG_PACKAGE_luci-app-shadowsocks-libev=y
          CONFIG_PACKAGE_luci-app-ssr-plus=m
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Xray=y
          CONFIG_PACKAGE_luci-app-ssrserver-python=m
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          CONFIG_PACKAGE_luci-app-v2ray-server=m
          # CONFIG_PACKAGE_luci-app-vlmcsd is not set
          CONFIG_PACKAGE_luci-app-vssr=y
          CONFIG_PACKAGE_luci-app-vssr_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-vssr_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray=y
          # CONFIG_PACKAGE_luci-app-wol is not set
          CONFIG_PACKAGE_luci-i18n-ssr-plus-zh-cn=m
          CONFIG_PACKAGE_luci-i18n-ssrserver-python-zh-cn=m
          CONFIG_PACKAGE_luci-i18n-v2ray-server-zh-cn=m
          CONFIG_PACKAGE_microsocks=m
          CONFIG_PACKAGE_naiveproxy=m
          CONFIG_PACKAGE_nspr=m
          CONFIG_PACKAGE_python3=m
          CONFIG_PACKAGE_python3-asyncio=m
          CONFIG_PACKAGE_python3-base=m
          CONFIG_PACKAGE_python3-cgi=m
          CONFIG_PACKAGE_python3-cgitb=m
          CONFIG_PACKAGE_python3-codecs=m
          CONFIG_PACKAGE_python3-ctypes=m
          CONFIG_PACKAGE_python3-dbm=m
          CONFIG_PACKAGE_python3-decimal=m
          CONFIG_PACKAGE_python3-distutils=m
          CONFIG_PACKAGE_python3-email=m
          CONFIG_PACKAGE_python3-gdbm=m
          CONFIG_PACKAGE_python3-light=m
          CONFIG_PACKAGE_python3-logging=m
          CONFIG_PACKAGE_python3-lzma=m
          CONFIG_PACKAGE_python3-multiprocessing=m
          CONFIG_PACKAGE_python3-ncurses=m
          CONFIG_PACKAGE_python3-openssl=m
          CONFIG_PACKAGE_python3-pydoc=m
          CONFIG_PACKAGE_python3-sqlite3=m
          CONFIG_PACKAGE_python3-unittest=m
          CONFIG_PACKAGE_python3-urllib=m
          CONFIG_PACKAGE_python3-xml=m
          CONFIG_PACKAGE_redsocks2=m
          CONFIG_PACKAGE_resolveip=m
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=m
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=m
          CONFIG_PACKAGE_shadowsocksr-libev-alt=m
          CONFIG_PACKAGE_shadowsocksr-libev-server=m
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=m
          CONFIG_PACKAGE_simple-obfs=m
          CONFIG_PACKAGE_tcping=m
          CONFIG_PACKAGE_terminfo=m
          CONFIG_PACKAGE_trojan=m
          CONFIG_PACKAGE_unzip=m
          CONFIG_PACKAGE_v2ray-plugin=m
          # CONFIG_PACKAGE_vlmcsd is not set
          # CONFIG_PACKAGE_wol is not set
          CONFIG_PACKAGE_xray-core=m
          CONFIG_SQLITE3_DYNAMIC_EXTENSIONS=y
          CONFIG_SQLITE3_FTS3=y
          CONFIG_SQLITE3_FTS4=y
          CONFIG_SQLITE3_FTS5=y
          CONFIG_SQLITE3_JSON1=y
          CONFIG_SQLITE3_RTREE=y
          CONFIG_XRAY_CORE_COMPRESS_UPX=y
          CONFIG_XRAY_CORE_PROVIDE_V2RAY_CORE=y
          CONFIG_boost-compile-visibility-hidden=y
          CONFIG_boost-runtime-shared=y
          CONFIG_boost-static-and-shared-libs=y
          CONFIG_boost-variant-release=y
          CONFIG_PACKAGE_ip-full=y
          CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
          CONFIG_PACKAGE_libelf=y
          CONFIG_PACKAGE_nlbwmon=y

          #
          # ========================固件定制部分结束========================
          #
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
        #run: make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
  

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
